#!/bin/sh
# # x-logo -- the Logo lang for x-lang
#
# ## tests/gen-harness.sh -- write tests/lib/harness.gen.x
#
# @description Generates the spec harness: the platform tower plus Logo's
#   turtle kernel, with no launcher.  Two absolute paths, both machine facts.
# @author [Jon Ruttan](jonruttan@gmail.com)
# @copyright 2026 Jon Ruttan
# @license MIT No Attribution (MIT-0)
#
# Usage: gen-harness.sh X_ROOT BUNDLE
set -e

X_ROOT="$1"
BUNDLE="$2"
OUT="$BUNDLE/tests/lib/harness.gen.x"

mkdir -p "$BUNDLE/tests/lib"

# WHICH x-base, and why it is not one path.  The contract says a bundle's
# harness loads boot/x-base.x -- the launcher-free AMALGAM, which carries no
# path literals and so loads from any cwd.  That is right, and "<root>/tests/
# works in both modes" holds for the runner.  It does NOT hold for the boot
# amalgams: an install has them at share/x/boot/, a checkout builds them into
# build/boot/, and <root>/boot/ exists in neither sense in a checkout.
#
# lib/x-base.x is NOT a substitute.  It is the SOURCE entry and opens with
# (include "lib/x-core.x") -- a root-relative literal that resolves only with
# the cwd at the repo root, which is exactly the addressing failure this
# bundle exists to not repeat.  Loading it from here fails with a bare
# "include: cannot open".
#
# So: probe, install layout first.
for _c in "$X_ROOT/boot/x-base.x" "$X_ROOT/build/boot/x-base.x"; do
	if [ -f "$_c" ]; then X_BASE="$_c"; break; fi
done
if [ -z "${X_BASE:-}" ]; then
	echo "x-logo: no launcher-free boot amalgam under $X_ROOT" >&2
	echo "  looked at boot/x-base.x and build/boot/x-base.x" >&2
	echo "  in a checkout, run 'make boot' in the x-lang tree first" >&2
	exit 1
fi

# Four things here are not obvious, and each costs an afternoon:
#
# 1. %install-root FIRST.  An amalgam carries no include literals, but its
#    deferred `import` forms resolve against the installed tree as it boots,
#    and module.x learns where that is from %install-root.  x.sh emits this
#    same line ahead of every boot entry; a harness loading an amalgam
#    directly has to emit it too.
#
# 2. boot/x-base.x, NOT a dialect entry.  he.x / xe.x / rn.x end with
#    (unless %batch? (do (%banner) (repl))) and would start a REPL underneath
#    the suite.  x-base.x is the launcher-free one, and being an amalgam it
#    carries no path literals, so it loads from any cwd.
#
# 3. %lang-root IS THE HARNESS'S JOB HERE.  At the prompt x.sh defines it,
#    because x.sh is what found the bundle; nothing found this one, so the
#    harness says.  The specs under tests/specs/ reach only the turtle kernel
#    and would pass without it -- it is emitted anyway, because the day a spec
#    touches logo/serve.x the failure would otherwise be an unbound symbol in
#    a file nobody changed, and the fix would be here rather than there.
#
# 4. logo/turtle, NOT run.x.  run.x is the ENTRY: it includes main.x, which
#    forks an HTTP server, binds :8080 and installs an exit hook.  Under a
#    spec suite that is a stray listener per batch and a port collision with
#    every other run on the machine.  turtle.x is the aggregator -- the whole
#    language, none of the plumbing -- which is exactly what the specs test.
cat > "$OUT" <<EOF
; harness.gen.x -- GENERATED by tests/gen-harness.sh.  Do not edit, do not
; commit: the two absolute paths below are facts of this machine.
(def %install-root "$X_ROOT")
(include "$X_BASE")
(import-path! "$BUNDLE")
(def %lang-root "$BUNDLE")
(import logo/turtle)
EOF
